baseURL = "https://lohan2000.github.io/proyecto-portafolio/"
languageCode = "en-us"
title = "Mi Portfolio"
theme = "hugo-PaperMod"

disableFingerprinting = true

[menu]
  [[menu.main]]
    identifier = "Persona 1"
    name = "Anjhelo Vela Yauri"
    url = "/Anjhelo-vela"
    weight = 1
  [[menu.main]]
    identifier = ""
    name = "Mirella Gavino"
    url = "/mirella-gavino/"
    weight = 2
  [[menu.main]]
    identifier = "Carlos Yudiño"
    name = "Carlos Yudiño"
    url = "/carlos/"
    weight = 3
  [[menu.main]]
    identifier = "gerardo"
    name = "Gerardo Campos"
    url = "/gerardo/"
    weight = 3
  [[menu.main]]
    identifier = "viter"
    name = "Viter Rodriguez"
    url = "/viter/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
