name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.7'
          extended: true

      - name: Build site
        run: hugo --minify --baseURL "https://LOHAN2000.github.io/proyecto-portafolio/"

      # Validación HTML usando el servicio W3C
      - name: Validate HTML
        run: |
          find public -name "*.html" | while read file; do
            echo "Validando $file..."
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Content-Type: text/html; charset=utf-8" \
              --data-binary "@$file" \
              "https://validator.w3.org/nu/?out=json")
            
            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "❌ Error validando $file (Código: $STATUS_CODE)"
              exit 1
            else
              echo "✅ $file válido"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
